LiberDent.Intranet/Controllers/CenyUslugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LiberDent.Data.Data;
using LiberDent.Data.Data.CMS;

namespace LiberDent.Intranet.Controllers
{
    public class CenyUslugController : Controller
    {
        private readonly LiberDentContext _context;

        public CenyUslugController(LiberDentContext context)
        {
            _context = context;
        }

        // GET: CenyUslug
        public async Task<IActionResult> Index()
        {
            return View(await _context.CenyUslug.ToListAsync());
        }

        // GET: CenyUslug/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cenyUslug = await _context.CenyUslug
                .FirstOrDefaultAsync(m => m.IdCenyUslug == id);
            if (cenyUslug == null)
            {
                return NotFound();
            }

            return View(cenyUslug);
        }

        // GET: CenyUslug/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CenyUslug/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCenyUslug,NazwaUslugi,CenaUslugi")] CenyUslug cenyUslug)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cenyUslug);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cenyUslug);
        }

        // GET: CenyUslug/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cenyUslug = await _context.CenyUslug.FindAsync(id);
            if (cenyUslug == null)
            {
                return NotFound();
            }
            return View(cenyUslug);
        }

        // POST: CenyUslug/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCenyUslug,NazwaUslugi,CenaUslugi")] CenyUslug cenyUslug)
        {
            if (id != cenyUslug.IdCenyUslug)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cenyUslug);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CenyUslugExists(cenyUslug.IdCenyUslug))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cenyUslug);
        }

        // GET: CenyUslug/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cenyUslug = await _context.CenyUslug
                .FirstOrDefaultAsync(m => m.IdCenyUslug == id);
            if (cenyUslug == null)
            {
                return NotFound();
            }

            return View(cenyUslug);
        }

        // POST: CenyUslug/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cenyUslug = await _context.CenyUslug.FindAsync(id);
            _context.CenyUslug.Remove(cenyUslug);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CenyUslugExists(int id)
        {
            return _context.CenyUslug.Any(e => e.IdCenyUslug == id);
        }
    }
}

LiberDent.Intranet/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LiberDent.Data.Data;
using LiberDent.Data.Data.CMS;

namespace LiberDent.Intranet.Controllers
{
    public class KontaktController : Controller
    {
        private readonly LiberDentContext _context;

        public KontaktController(LiberDentContext context)
        {
            _context = context;
        }

        // GET: Kontakt
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kontakt.ToListAsync());
        }

        // GET: Kontakt/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kontakt = await _context.Kontakt
                .FirstOrDefaultAsync(m => m.IdKontaktu == id);
            if (kontakt == null)
            {
                return NotFound();
            }

            return View(kontakt);
        }

        // GET: Kontakt/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kontakt/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKontaktu,TytułKontakt,NumerTelefonu,NazwaTelefonu,TrescKontaktu,PozycjaWyswietlania,CzyAktywny")] Kontakt kontakt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kontakt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kontakt);
        }

        // GET: Kontakt/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kontakt = await _context.Kontakt.FindAsync(id);
            if (kontakt == null)
            {
                return NotFound();
            }
            return View(kontakt);
        }

        // POST: Kontakt/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKontaktu,TytułKontakt,NumerTelefonu,NazwaTelefonu,TrescKontaktu,PozycjaWyswietlania,CzyAktywny")] Kontakt kontakt)
        {
            if (id != kontakt.IdKontaktu)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kontakt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KontaktExists(kontakt.IdKontaktu))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kontakt);
        }

        // GET: Kontakt/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kontakt = await _context.Kontakt
                .FirstOrDefaultAsync(m => m.IdKontaktu == id);
            if (kontakt == null)
            {
                return NotFound();
            }

            return View(kontakt);
        }

        // POST: Kontakt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kontakt = await _context.Kontakt.FindAsync(id);
            _context.Kontakt.Remove(kontakt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KontaktExists(int id)
        {
            return _context.Kontakt.Any(e => e.IdKontaktu == id);
        }
    }
}

LiberDent.Intranet/Controllers/ONasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LiberDent.Data.Data;
using LiberDent.Data.Data.CMS;

namespace LiberDent.Intranet.Controllers
{
    public class ONasController : Controller
    {
        private readonly LiberDentContext _context;

        public ONasController(LiberDentContext context)
        {
            _context = context;
        }

        // GET: ONas
        public async Task<IActionResult> Index()
        {
            return View(await _context.ONas.ToListAsync());
        }

        // GET: ONas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oNas = await _context.ONas
                .FirstOrDefaultAsync(m => m.IdONas == id);
            if (oNas == null)
            {
                return NotFound();
            }

            return View(oNas);
        }

        // GET: ONas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ONas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdONas,Naglowek,Tresc1,Tresc2")] ONas oNas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(oNas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(oNas);
        }

        // GET: ONas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oNas = await _context.ONas.FindAsync(id);
            if (oNas == null)
            {
                return NotFound();
            }
            return View(oNas);
        }

        // POST: ONas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdONas,Naglowek,Tresc1,Tresc2")] ONas oNas)
        {
            if (id != oNas.IdONas)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oNas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ONasExists(oNas.IdONas))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(oNas);
        }

        // GET: ONas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oNas = await _context.ONas
                .FirstOrDefaultAsync(m => m.IdONas == id);
            if (oNas == null)
            {
                return NotFound();
            }

            return View(oNas);
        }

        // POST: ONas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var oNas = await _context.ONas.FindAsync(id);
            _context.ONas.Remove(oNas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ONasExists(int id)
        {
            return _context.ONas.Any(e => e.IdONas == id);
        }
    }
}

LiberDent.Intranet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using LiberDent.Data.Data.Account
@using LiberDent.Data.Data
@using LiberDent.Data.Data.Slownikowe
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject LiberDentContext db
@{ 
    DaneLekarza lekarz = db.DaneLekarza.Where(d => d.Uzytkownik.Id == UserManager.GetUserId(User)).FirstOrDefault();
    int? poz = null;
    if(lekarz !=null)
    {
        poz = db.PoziomUprawnien.Find(lekarz.IdPoziomUprawnien).NumerUprawnien;
    }

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - LiberDent.Intranet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous" />
    <link href="css/bootstrap-4-navbar.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        @if (SignInManager.IsSignedIn(User))
        {
            if (poz > 1)
            {
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home">LiberDent Intranet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">

                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">Strona główna <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarstrona" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Zarządzanie stroną główną</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarstrona">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="GodzinyOtwarcia" asp-action="Index">Godziny otwarcia</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Kontakt" asp-action="Index">Kontakt</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Powitanie" asp-action="Index">Powitanie</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="ONas" asp-action="Index">ONas</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarpersonel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Zarządzanie personelem</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarpersonel">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="TytulNaukowy" asp-action="Index">Tytuły naukowe</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="DaneOPersonelu" asp-action="Index">Dane o personelu</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Stanowiska" asp-action="Index">Stanowiska</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Register">Rejestracja</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="PoziomUprawnien" asp-action="Index">Poziomy uprawnień</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarwizyty" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Zarządzanie wizytami</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarwizyty">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="CenyUslug" asp-action="Index">Ceny usług</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="RodzajeWizyty" asp-action="Index">RodzajeWizyty</a>
                                </li>
                            </ul>
                        </li>
                        
                        @await Html.PartialAsync("_LoginPartial")
                    </ul>
                </div>
            }
            else
            {
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home">LiberDent Intranet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">

                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">Strona główna <span class="sr-only">(current)</span></a>
                        </li>
                        @await Html.PartialAsync("_LoginPartial")
                    </ul>
                </div>
            }
        }
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

    <script src="js/bootstrap-4-navbar.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>